Petru dev branch
StandUpStrategische/Strategisch pull request #21
Opened 2023-09-04 16:29 UTC by PetruQA-Stk

PetruStandUp05.09.23

2023-09-04 16:32 UTC, PetruQA-Stk commented
MergePetru05.09.23 bitte um review

2023-09-05 07:10 UTC, yvesngamini requested changes

2023-09-05 07:10 UTC, yvesngamini commented on tagesPlan05_09_23.json
> +    "Intake Übungslaufe mit": " N/A",
warum steht der @julessokoudjou Daten hier !!!

2023-09-05 07:12 UTC, yvesngamini commented
@PetruWalter, bitte ändere deine JSON-Datei

2023-09-05 07:27 UTC, closed without merging